### ISSUE TITLE
second request for regional office phone numbers

### ISSUE THREAD

**Issue by tweetsas** [mchat/call-my-congress#7] opened 2016-11-28 17:44 UTC
Hi - this is awesome!!!

we are hearing from congressional offices that the local office phone are important.  It would be great if you added that info.

Many thanks,

sas

**Comment by mchat** [comment] 2016-11-28 21:15
sas, thank you for the feedback and for the request! I'm going to close out this request as a duplicate of #3. I'd prefer to keep one request open for each unique feature, but feel free to [add your comments or reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to #3 to indicate your support! The more support or comments there are on an issue, the more that I know that people would like to see that feature.

**Closed by mchat** 2016-11-28 21:15 UTC
